/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from '@dojoengine/recs';

export function defineContractComponents(world: World) {
    return {
        Auction: (() => {
            return defineComponent(
                world,
                {
                    game_id: RecsType.Number,
                    item_id: RecsType.Number,
                    target_price: RecsType.BigInt,
                    decay_constant_mag: RecsType.BigInt,
                    decay_constant_sign: RecsType.Boolean,
                    max_sellable: RecsType.BigInt,
                    time_scale_mag: RecsType.BigInt,
                    time_scale_sign: RecsType.Boolean,
                    start_time: RecsType.Number,
                    sold: RecsType.Number,
                },
                {
                    metadata: {
                        name: 'Auction',
                        types: [],
                    },
                }
            );
        })(),
        Brew: (() => {
            return defineComponent(
                world,
                {
                    game_id: RecsType.Number,
                    player_id: RecsType.String,
                    batch_id: RecsType.Number,
                    batch_key: RecsType.Number,
                    owner: RecsType.String,
                    beer_id: RecsType.Number,
                    time_built: RecsType.Number,
                    status: RecsType.Number,
                },
                {
                    metadata: {
                        name: 'Brew',
                        types: [],
                    },
                }
            );
        })(),
        BrewBatchTrack: (() => {
            return defineComponent(
                world,
                { game_id: RecsType.Number, owner: RecsType.String, count: RecsType.Number },
                {
                    metadata: {
                        name: 'BrewBatchTrack',
                        types: [],
                    },
                }
            );
        })(),
        FarmArea: (() => {
            return defineComponent(
                world,
                {
                    game_id: RecsType.Number,
                    player_id: RecsType.String,
                    area_id: RecsType.Number,
                    area_type: RecsType.Number,
                    time_built: RecsType.Number,
                },
                {
                    metadata: {
                        name: 'FarmArea',
                        types: [],
                    },
                }
            );
        })(),
        Game: (() => {
            return defineComponent(
                world,
                {
                    game_id: RecsType.Number,
                    start_time: RecsType.Number,
                    status: RecsType.Number,
                    number_players: RecsType.Number,
                    max_players: RecsType.Number,
                    game_length: RecsType.Number,
                    password: RecsType.BigInt,
                    entry_fee: RecsType.Number,
                    seed: RecsType.Number,
                },
                {
                    metadata: {
                        name: 'Game',
                        types: [],
                    },
                }
            );
        })(),
        GameTracker: (() => {
            return defineComponent(
                world,
                { entity_id: RecsType.Number, count: RecsType.Number },
                {
                    metadata: {
                        name: 'GameTracker',
                        types: [],
                    },
                }
            );
        })(),
        IndulgenceAuction: (() => {
            return defineComponent(
                world,
                {
                    game_id: RecsType.Number,
                    auction_id: RecsType.Number,
                    price: RecsType.Number,
                    highest_bid_player_id: RecsType.String,
                    expiry: RecsType.Number,
                    auction_id_value: RecsType.Number,
                    status: RecsType.Number,
                },
                {
                    metadata: {
                        name: 'IndulgenceAuction',
                        types: [],
                    },
                }
            );
        })(),
        IndulgenceAuctionCount: (() => {
            return defineComponent(
                world,
                { game_id: RecsType.Number, count: RecsType.Number },
                {
                    metadata: {
                        name: 'IndulgenceAuctionCount',
                        types: [],
                    },
                }
            );
        })(),
        ItemBalance: (() => {
            return defineComponent(
                world,
                { game_id: RecsType.Number, player_id: RecsType.String, item_id: RecsType.Number, balance: RecsType.Number },
                {
                    metadata: {
                        name: 'ItemBalance',
                        types: [],
                    },
                }
            );
        })(),
        Joined: (() => {
            return defineComponent(
                world,
                { game_id: RecsType.Number, address: RecsType.BigInt, joined: RecsType.Boolean },
                {
                    metadata: {
                        name: 'Joined',
                        types: [],
                    },
                }
            );
        })(),
        Ownership: (() => {
            return defineComponent(
                world,
                { entity_id: RecsType.Number, owner: RecsType.BigInt },
                {
                    metadata: {
                        name: 'Ownership',
                        types: [],
                    },
                }
            );
        })(),
        Player: (() => {
            return defineComponent(
                world,
                { game_id: RecsType.Number, player_id: RecsType.String, name: RecsType.BigInt },
                {
                    metadata: {
                        name: 'Player',
                        types: [],
                    },
                }
            );
        })(),
        TavernAuction: (() => {
            return defineComponent(
                world,
                {
                    game_id: RecsType.Number,
                    item_id: RecsType.Number,
                    target_price: RecsType.BigInt,
                    decay_constant_mag: RecsType.BigInt,
                    decay_constant_sign: RecsType.Boolean,
                    per_time_unit: RecsType.BigInt,
                    start_time: RecsType.Number,
                    sold: RecsType.Number,
                },
                {
                    metadata: {
                        name: 'TavernAuction',
                        types: [],
                    },
                }
            );
        })(),
        Trade: (() => {
            return defineComponent(
                world,
                {
                    entity_id: RecsType.Number,
                    game_id: RecsType.Number,
                    item_id: RecsType.Number,
                    quantity: RecsType.Number,
                    price: RecsType.Number,
                    status: RecsType.Number,
                    player_id: RecsType.String,
                    game_id_value: RecsType.Number,
                },
                {
                    metadata: {
                        name: 'Trade',
                        types: [],
                    },
                }
            );
        })(),
        TradeTrack: (() => {
            return defineComponent(
                world,
                { game_id: RecsType.Number, count: RecsType.Number },
                {
                    metadata: {
                        name: 'TradeTrack',
                        types: [],
                    },
                }
            );
        })(),
    };
}
